app/controllers/CatalogController.php
<?php

namespace app\controllers;

use Yii;
use yii\easyii\modules\catalog\api\Catalog;
use yii\easyii\modules\catalog\models\Category;
use yii\easyii\modules\catalog\api\CategoryObject;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use app\helpers\CatalogHelper;


class CatalogController extends \yii\web\Controller
{
    public function actionIndex(){
        $cat_objects = Category::find()
            ->where(['id' => [1,2,3,4,5]])
            ->orderBy(['order_num' => SORT_ASC])
            ->all();
        $cats = ArrayHelper::map($cat_objects, 'id', function($cat){
            return new CategoryObject($cat);
        });
        
        
        return $this->render('index', [
            'cats' => $cats,
        ]);
    }
    
    
    public function actionCat($slug){
        $cat = Catalog::cat($slug);
        if(!$cat){
            throw new NotFoundHttpException('Категория не найдена.');
        }
        $child_cats = array_filter($cat->getChildren(), function($cat){
            return $cat->id != '26';
        });
        
        $items = null;
        if(!count($child_cats)){
            $items = $cat->getItems([
                'pagination' => ['defaultPageSize' => 16],
                'orderBy' => ['id' => SORT_ASC],
            ]);
        }
        
        $osnastki = null;
        if($slug == 'pecati'){
            $osnastki_objects = Category::find()
                ->where(['id' => [22,23,24,25]])
                ->orderBy(['order_num' => SORT_ASC])
                ->all();
            $osnastki = ArrayHelper::map($osnastki_objects, 'id', function($cat){
                $cat->parent = 3;
                return new CategoryObject($cat);
            });
        }
        
        // ВСЕ КАТЕГОРИИ (ДЛЯ МЕНЮ)
        $all_cats_objects = Category::find()
            ->where(['id' => [1,2,3,4,5]])
            ->select(['id', 'slug', 'title'])
            ->orderBy(['order_num' => SORT_ASC])
            ->all();
        $all_cats = ArrayHelper::map($all_cats_objects, 'id', function($cat){
            return new CategoryObject($cat);
        });
        
        $form_model = new \app\models\forms\CatalogForm();
        if(Yii::$app->request->isAjax){
            if($form_model->load(Yii::$app->request->post()) && $form_model->validate()){
                $form_model->save();
                return $this->asJson($form_model->toArray());
            }
        }
        
        return $this->render('cat', [
            'cat' => $cat,
            'child_cats' => $child_cats,
            'osnastki' => $osnastki,
            'all_cats' => $all_cats,
            'items' => $items,
            'form_model' => $form_model,
        ]);
    }
    
    
    
    
    public function actionSubcat($slug){
        $subcat = Catalog::cat($slug);
        $items = $subcat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        
        $form_model = new \app\models\forms\CatalogForm();
        if(Yii::$app->request->isAjax){
            if($form_model->load(Yii::$app->request->post()) && $form_model->validate()){
                $form_model->save();
                return $this->asJson($form_model->toArray());
            }
        }
        
        return $this->render('subcat', [
            'subcat' => $subcat,
            'items' => $items,
            'form_model' => $form_model,
        ]);
    }
    
    
    public function actionTools(){
        return $this->render('tools', [
            'tool_cats' => CatalogHelper::getToolCats(),
        ]);
    }
    
    public function actionToolsExamples($slug, $a = null){
        if(CatalogHelper::getToolCatConfig($slug, 'hidden') && $a !== null){
            CatalogHelper::buyHiddenItem($slug);
            if($a === 'buy'){
                $this->redirect(['/shopcart']);
            }
            else{
                $this->redirect(['/catalog/' . $a . '?a=buy']);
            }
        }
        $category = Catalog::cat($slug);
        return $this->render('tools-examples', [
            'category' => $category,
            'cat_config' => CatalogHelper::getToolCatConfig($slug),
        ]);
    }
    
    public function actionStamps(){
        return $this->render('stamps', [
            'cat' => Catalog::cat('stamps'),
            'by_scetch' => Catalog::cat('by-scetch'),
            'stampy' => Catalog::cat('stampy'),
            'faximile' => Catalog::cat('faximile'),
            'ekslibrisy' => Catalog::cat('ekslibrisy'),
        ]);
    }
    
    public function actionByScetch(){
        $path_info = explode('/', Yii::$app->request->getPathInfo());
        $slug = $path_info[count($path_info) - 1];
        $cat = Catalog::cat($slug);
        $model = new \app\models\ByScetchForm(['form_title' => $cat->title]);
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        return $this->render('by-scetch', [
            'cat' => $cat,
            'model' => $model,
        ]);
    }
    
    public function actionPlombiryIPlombiratory(){
        $cat = Catalog::cat('plombiry-i-plombiratory');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('plombiry-i-plombiratory', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionStampyTools(){
        $cat = Catalog::cat('stampy-tools');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('stampy-tools', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionEkslibrisy(){
        $cat = Catalog::cat('ekslibrisy');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('ekslibrisy', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionEkslibris($slug){
        $item = Catalog::get($slug);
        $model = new \app\models\EkslibrisForm([
            'form_title' => 'Экслибрис (' . $item->title . ')'
        ]);
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        return $this->render('ekslibris', [
            'item' => $item,
            'model' => $model,
        ]);
    }
    
    
    public function actionStampy(){
        $cat = Catalog::cat('stampy');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 12],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('stampy', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    public function actionDateryINumeratory(){
        $categories = Category::find()->where(['in', 'slug', [
            'stampy-samonabornye',
            'pecati-samonabornye',
            'datery',
            'numeratory',
            'datery-so-svobodnym-polem',
            'avtomaticeskie-numeratory',
            'samonabornyj-dater',
            'smennye-poduski',
        ]])->orderBy(['id' => SORT_ASC])->all();
        $subcats = array_map(function($category){
            return new CategoryObject($category);
        }, $categories);
        $different = Catalog::cat('datery-different');
        return $this->render('datery-i-numeratory', [
            'cat' => Catalog::cat('datery-i-numeratory'),
            'items' => $different->getItems(['orderBy' => ['id' => SORT_ASC]]),
            'subcats' => $subcats,
        ]);
    }
    public function actionDn($slug){
        $cat = Catalog::cat($slug);
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 4],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('dn', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionSmennyePoduski(){
        $request = Yii::$app->request;
        if(!empty($request->post('form')) && !empty($request->post('id'))){
            return $this->redirect(['site/buy', 'id' => $request->post('id')]);
        }
        return $this->render('smennye-poduski', [
            'cat' => Catalog::cat('smennye-poduski'),
            'grm' => Catalog::cat('sp-grm'),
            'colop' => Catalog::cat('sp-colop'),
            'trodat' => Catalog::cat('sp-trodat'),
        ]);
    }
}

app/views/layouts/chunks/_callback_float.php
<?php
/* @var $this \yii\web\View */
use yii\bootstrap\Html;
use yii\bootstrap\Modal;
use yii\bootstrap\ActiveForm;
use yii\widgets\MaskedInput;

Modal::begin([
    'id' => 'float-button-modal',
    'header' => '<h3 class="text-center margin-b-0">Перезвоним за 8 секунд</h3>',
]);
$form_model = new \app\models\forms\CallbackForm();
$form = ActiveForm::begin([
    'action' => ['/call'],
]);
?>
<?=$form->field($form_model, 'phone')
    ->textInput()
    ->label('Введите ваш контактный телефон')
    ->widget(MaskedInput::className(), [
        'mask' => '+7 (999) 999-99-99'
    ]);?>
<p class="text-center">
    <?=Html::submitButton('Жду звонка', ['class' => 'btn btn-info btn-lg']); ?>
</p>
                
<?php
ActiveForm::end();
Modal::end();
?>

app/views/layouts/chunks/_cat.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */

use yii\helpers\Url;
use yii\bootstrap\Html;
$url_data = isset($order_type) ?
    ['/order-type', 'category' => $cat->slug] : ['/catalog/cat', 'slug' => $cat->slug];
?>
<div class="col-xs-12 col-sm-6 col-md-3 col-lg-5ths">
    <a class="item" href="<?=Url::to($url_data);?>">
        <div class="item-img-wrapper">
            <?=Html::img($cat->thumb(null, 400), ['alt' => $cat->title]);?>
        </div>
        <div class="item-title"><?=$cat->title;?></div>
    </a>
</div>

app/views/layouts/chunks/_footer.php
<?php
use app\models\forms\MainContactForm;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
$asset = \app\assets\AppAsset::register($this);
?>
<a class="anchor" id="contact"></a>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <p class="phone">
                    <?=Html::a($phone, 'tel:' . preg_replace('/[^\+\d]/', '', $phone));?>
                </p>
                <p class="mail">
                    <?=Html::a($email, 'mailto:' . $email);?>
                </p>
                <p>344006, РФ, г. Ростов-на-Дону, ﻿пр. Кировский, 37</p>
                <p>Пн.-Пт. с 9.00 до 18:00</br>Сб.-Вс. — выходной.</br>Выдача товара осуществляется в будние дни с 9.00 до 18.00</p>
            </div>
            <div class="col-xs-12 col-sm-6">
                <h3>Оставьте сообщение</h3>
                
                <?php 
                    $form_model = new MainContactForm();
                    $form = ActiveForm::begin([
                        'action' => '/send-message',
                        'id' => 'main-contact-form',
                    ]);
                ?>
                
                <?=$form->field($form_model, 'name')
                    ->textInput(['placeholder' => $form_model->getAttributeLabel('name')])
                    ->label(false);?>
                
                <?=$form->field($form_model, 'email')
                    ->textInput(['placeholder' => $form_model->getAttributeLabel('email')])
                    ->label(false);?>

                <?=$form->field($form_model, 'phone')->widget(\yii\widgets\MaskedInput::className(), [
                    'mask' => '+7 (999) 999 99 99',
                    'options' => [
                        'autocomplete' => 'off',
                        'class' => 'form-control',
                        'placeholder' => $form_model->getAttributeLabel('phone')
                    ],
                ])->label(false);?>

                <?=$form->field($form_model, 'message')->textarea([
                    'placeholder' => $form_model->getAttributeLabel('message'),
                ])->label(false);?>
                
                <?=Html::submitButton('Отправить', [
                    'class' => 'btn btn-info btn-lg'
                ])?>
                    
                <?php ActiveForm::end(); ?>
                
            </div>
        </div>
    </div>
</footer>

<?php
$this->registerJs(<<<JS
    var main_contact_form = jQuery('#main-contact-form');
    
    main_contact_form.on('beforeSubmit.yii', function() {
        var data = main_contact_form.serialize();
        jQuery.post(main_contact_form.attr('action'), data, function(data){
            if(data.success){
                metrikaReachGoal('application');
                document.location = '/success';
            }
        });
        return false;
    });
        
        
    jQuery('form[action="/call"]').on('beforeSubmit.yii', function(){
        metrikaReachGoal('application');
    });
JS
);
?>

app/views/layouts/chunks/_header.php
<?php
use yii\bootstrap\Html;
$asset = \app\assets\AppAsset::register($this);
?>
<div class="header" id="navbar">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-3 col-md-3 col-sm-4">
                <?=Html::a(
                    '<img src="'.$asset->baseUrl.'/img/logo.png" class="header-logo">',
                    ['/']
                );?>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4">
                <?=Html::a(
                    $phone, 'tel:' . preg_replace('/[^\+\d]/', '', $phone),
                    ['class' => 'header-phone']
                );?>
            </div>
            <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
                <?=Html::a(
                    $email, 'mailto:' . $email,
                    ['class' => 'header-email']
                );?>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4">
                <?=Html::button('Перезвонить за наш счет', [
                    'class' => 'btn btn-2 btn-default btn-sm header-callback-btn',
                    'data-toggle' => 'modal',
                    'data-target' => '#float-button-modal',
                ]);?>
            </div>
        </div>
    </div>
</div>

app/views/layouts/chunks/_item.php
<?php
/* @var $item \yii\easyii\modules\catalog\api\ItemObject */

use yii\helpers\Url;
use yii\helpers\Html;

$a = Yii::$app->request->get('a');
$url_data = $a === 'buy' ?
    ['site/buy', 'id' => $item->id]
    : ['site/buy', 'id' => $item->id, 'a' => 'tools'];
?>
<a class="item" href="<?=Url::toRoute($url_data);?>">
    <div class="item-img-wrapper">
        <?=Html::img($item->thumb(245, 245), ['alt' => $item->title]);?>
    </div>
    <div class="item-title"><?=$item->title;?></div>
</a>

app/views/layouts/chunks/_jivosite.php
<?php if(!YII_DEBUG && (YII_ENV != 'dev')): ?>
    <!-- BEGIN JIVOSITE CODE {literal} -->
    <script type='text/javascript'>
    (function(){ var widget_id = '928QSwnzNx';var d=document;var w=window;function l(){
    var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script>
    <!-- {/literal} END JIVOSITE CODE -->
<?php endif; ?>

app/views/layouts/chunks/_subcat.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */

use yii\helpers\Url;
use yii\bootstrap\Html;
?>
<div class="col-xs-12 col-sm-3 col-md-2">
    <a class="item" href="<?=Url::toRoute(['catalog/subcat', 'cat' => $cat->model->parent,  'slug' => $cat->slug]);?>">
        <div class="item-img-wrapper">
            <?=Html::img($cat->thumb(null, 400), ['alt' => $cat->title]);?>
        </div>
        <div class="item-title"><?=$cat->title;?></div>
    </a>
</div>

app/views/layouts/chunks/_subcat_2.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */

use yii\helpers\Url;
use yii\bootstrap\Html;
use app\helpers\CatalogHelper;
$a = Yii::$app->request->get('a');
?>
<div class="col-xs-12 col-sm-6 col-md-3">
    <a class="item" href="<?=Url::toRoute(['catalog/index', 'slug' => $cat->slug, 'a' => $a]);?>">
        <div class="item-img-wrapper">
            <?=Html::img($cat->thumb(null, 400), ['alt' => $cat->title]);?>
        </div>
        <div class="item-title"><?=$cat->title;?></div>
        <div class="item-price">
            Цена от <?=CatalogHelper::getMinPrice($cat);?> руб.
        </div>
    </a>
</div>

app/views/layouts/chunks/_tool_cat.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */

use yii\helpers\Url;
use yii\bootstrap\Html;
use app\helpers\CatalogHelper;
$variant = $variant ? $variant : null;
$a = Yii::$app->request->get('a');
$b = Yii::$app->request->get('b');
?>
<div class="col-xs-12 col-sm-6 col-md-3">
    <a class="item" href="<?=Url::toRoute(['catalog/tools-examples',
            'slug' => $cat->slug, 'a' => $a, 'b' => $b]);?>">
        <div class="item-img-wrapper">
            <?=Html::img($cat->thumb(null, 400), ['alt' => $cat->title]);?>
        </div>
        <div class="item-title"><?=$cat->title;?></div>
        <div class="item-flying-info">
            <div class="item-flying-info-inner">
                <span class="item-flying-info-bottom">
                    от <?=CatalogHelper::getMinPrice($cat);?> руб.
                </span>
            </div>
        </div>
    </a>
</div>

app/views/layouts/chunks/_tool_item.php
<?php
/* @var $item \yii\easyii\modules\catalog\api\ItemObject */

use yii\helpers\Url;
use yii\helpers\Html;
$a = Yii::$app->request->get('a');
$b = Yii::$app->request->get('b');
$url_data = $a === 'buy' ?
    ['site/buy', 'id' => $item->id]
    : ['site/buy', 'id' => $item->id, 'a' => $a, 'b' => $b];
?>
<a class="item" href="<?=Url::toRoute($url_data);?>">
    <div class="item-img-wrapper">
        <?=Html::img($item->thumb(null, 250), ['alt' => $item->title]);?>
    </div>
    <div class="item-title"><?=$item->title;?></div>
    <div class="item-price">Цена: <?=$item->price;?> руб.</div>
</a>

app/views/layouts/chunks/counter.php
<p class="text-center margin-t-30">
    <span class="counter" data-counter-seconds="<?=$seconds;?>"><?=$seconds;?></span>
</p>