app/controllers/CatalogController.php
<?php

namespace app\controllers;

use Yii;
use yii\easyii\modules\catalog\api\Catalog;
use yii\easyii\modules\catalog\models\Category;
use yii\easyii\modules\catalog\api\CategoryObject;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use app\helpers\CatalogHelper;


class CatalogController extends \yii\web\Controller
{
    public function actionIndex(){
        $cat_objects = Category::find()
            ->where(['id' => [1,2,3,4,5]])
            ->orderBy(['order_num' => SORT_ASC])
            ->all();
        $cats = ArrayHelper::map($cat_objects, 'id', function($cat){
            return new CategoryObject($cat);
        });
        
        
        return $this->render('index', [
            'cats' => $cats,
        ]);
    }
    
    
    public function actionCat($slug){
        $cat = Catalog::cat($slug);
        if(!$cat){
            throw new NotFoundHttpException('Категория не найдена.');
        }
        $child_cats = array_filter($cat->getChildren(), function($cat){
            return $cat->id != '26';
        });
        
        $items = null;
        if(!count($child_cats)){
            $items = $cat->getItems([
                'pagination' => ['defaultPageSize' => 16],
                'orderBy' => ['id' => SORT_ASC],
            ]);
        }
        
        $osnastki = null;
        if($slug == 'pecati'){
            $osnastki_objects = Category::find()
                ->where(['id' => [22,23,24,25]])
                ->orderBy(['order_num' => SORT_ASC])
                ->all();
            $osnastki = ArrayHelper::map($osnastki_objects, 'id', function($cat){
                $cat->parent = 3;
                return new CategoryObject($cat);
            });
        }
        
        // ВСЕ КАТЕГОРИИ (ДЛЯ МЕНЮ)
        $all_cats_objects = Category::find()
            ->where(['id' => [1,2,3,4,5]])
            ->select(['id', 'slug', 'title'])
            ->orderBy(['order_num' => SORT_ASC])
            ->all();
        $all_cats = ArrayHelper::map($all_cats_objects, 'id', function($cat){
            return new CategoryObject($cat);
        });
        
        $form_model = new \app\models\forms\CatalogForm();
        if(Yii::$app->request->isAjax){
            if($form_model->load(Yii::$app->request->post()) && $form_model->validate()){
                $form_model->save();
                return $this->asJson($form_model->toArray());
            }
        }
        
        return $this->render('cat', [
            'cat' => $cat,
            'child_cats' => $child_cats,
            'osnastki' => $osnastki,
            'all_cats' => $all_cats,
            'items' => $items,
            'form_model' => $form_model,
        ]);
    }
    
    
    
    
    public function actionSubcat($slug){
        $subcat = Catalog::cat($slug);
        $items = $subcat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        
        $form_model = new \app\models\forms\CatalogForm();
        if(Yii::$app->request->isAjax){
            if($form_model->load(Yii::$app->request->post()) && $form_model->validate()){
                $form_model->save();
                return $this->asJson($form_model->toArray());
            }
        }
        
        return $this->render('subcat', [
            'subcat' => $subcat,
            'items' => $items,
            'form_model' => $form_model,
        ]);
    }
    
    
    public function actionTools(){
        return $this->render('tools', [
            'tool_cats' => CatalogHelper::getToolCats(),
        ]);
    }
    
    public function actionToolsExamples($slug, $a = null){
        if(CatalogHelper::getToolCatConfig($slug, 'hidden') && $a !== null){
            CatalogHelper::buyHiddenItem($slug);
            if($a === 'buy'){
                $this->redirect(['/shopcart']);
            }
            else{
                $this->redirect(['/catalog/' . $a . '?a=buy']);
            }
        }
        $category = Catalog::cat($slug);
        return $this->render('tools-examples', [
            'category' => $category,
            'cat_config' => CatalogHelper::getToolCatConfig($slug),
        ]);
    }
    
    public function actionStamps(){
        return $this->render('stamps', [
            'cat' => Catalog::cat('stamps'),
            'by_scetch' => Catalog::cat('by-scetch'),
            'stampy' => Catalog::cat('stampy'),
            'faximile' => Catalog::cat('faximile'),
            'ekslibrisy' => Catalog::cat('ekslibrisy'),
        ]);
    }
    
    public function actionByScetch(){
        $path_info = explode('/', Yii::$app->request->getPathInfo());
        $slug = $path_info[count($path_info) - 1];
        $cat = Catalog::cat($slug);
        $model = new \app\models\ByScetchForm(['form_title' => $cat->title]);
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        return $this->render('by-scetch', [
            'cat' => $cat,
            'model' => $model,
        ]);
    }
    
    public function actionPlombiryIPlombiratory(){
        $cat = Catalog::cat('plombiry-i-plombiratory');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('plombiry-i-plombiratory', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionStampyTools(){
        $cat = Catalog::cat('stampy-tools');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('stampy-tools', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionEkslibrisy(){
        $cat = Catalog::cat('ekslibrisy');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('ekslibrisy', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionEkslibris($slug){
        $item = Catalog::get($slug);
        $model = new \app\models\EkslibrisForm([
            'form_title' => 'Экслибрис (' . $item->title . ')'
        ]);
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        return $this->render('ekslibris', [
            'item' => $item,
            'model' => $model,
        ]);
    }
    
    
    public function actionStampy(){
        $cat = Catalog::cat('stampy');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 12],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('stampy', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    public function actionDateryINumeratory(){
        $categories = Category::find()->where(['in', 'slug', [
            'stampy-samonabornye',
            'pecati-samonabornye',
            'datery',
            'numeratory',
            'datery-so-svobodnym-polem',
            'avtomaticeskie-numeratory',
            'samonabornyj-dater',
            'smennye-poduski',
        ]])->orderBy(['id' => SORT_ASC])->all();
        $subcats = array_map(function($category){
            return new CategoryObject($category);
        }, $categories);
        $different = Catalog::cat('datery-different');
        return $this->render('datery-i-numeratory', [
            'cat' => Catalog::cat('datery-i-numeratory'),
            'items' => $different->getItems(['orderBy' => ['id' => SORT_ASC]]),
            'subcats' => $subcats,
        ]);
    }
    public function actionDn($slug){
        $cat = Catalog::cat($slug);
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 4],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('dn', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionSmennyePoduski(){
        $request = Yii::$app->request;
        if(!empty($request->post('form')) && !empty($request->post('id'))){
            return $this->redirect(['site/buy', 'id' => $request->post('id')]);
        }
        return $this->render('smennye-poduski', [
            'cat' => Catalog::cat('smennye-poduski'),
            'grm' => Catalog::cat('sp-grm'),
            'colop' => Catalog::cat('sp-colop'),
            'trodat' => Catalog::cat('sp-trodat'),
        ]);
    }
}

app/views/catalog/by-scetch.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */

use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\bootstrap\ActiveForm;
use yii\widgets\MaskedInput;
use yii\bootstrap\Html;

$asset = AppAsset::register($this);
$this->title = Html::encode($cat->title);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 margin-b-0">
            <div class="complex-img-container">
                <?=Html::img($asset->baseUrl . '/img/' . $cat->slug . '/1.jpg', ['class' => 'complex-img']);?>
                <?=Html::img($asset->baseUrl . '/img/' . $cat->slug . '/3.jpg', ['class' => 'complex-img-arrow']);?>
                <?=Html::img($asset->baseUrl . '/img/' . $cat->slug . '/2.jpg', ['class' => 'complex-img']);?>
            </div>
            
            <div class="row">
                <div class="col-md-8 col-md-offset-2 margin-b-0">
                    <?php $form = ActiveForm::begin(); ?>

                    <?=$form->field($model, 'name')
                        ->textInput(['placeholder' => $model->getAttributeLabel('name')])->label(false);?>
                    
                    <?=$form->field($model, 'phone')
                        ->label(false)
                        ->widget(MaskedInput::className(), [
                            'mask' => '+7(999) 999-99-99',
                            'options' => [
                                'placeholder' => $model->getAttributeLabel('phone'),
                                'class' => 'form-control'
                            ],
                        ]);?>
                    
                    <?=$form->field($model, 'file')->fileInput();?>
                    
                    <?=$form->field($model, 'message')
                        ->textarea(['placeholder' => $model->getAttributeLabel('message')])->label(false);?>
                    
                    <div class="text-center">
                        <?=Html::submitButton('Отправить', ['class' => 'btn btn-danger']);?>
                    </div>
                    
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/catalog/cat.php
<?php
/* @var $cat \yii\easyii\modules\article\api\CategoryObject */
/* @var $child_cats \yii\easyii\modules\article\api\CategoryObject[] */

use yii\helpers\Url;
use yii\helpers\Html;

$request = Yii::$app->request;
$a = $request->get('a');
$cat_slug = $request->get('slug');
$this->title = Html::encode($cat->title);
?>
<div class="container">
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row auto-clear">
        <?php foreach($child_cats as $subcat): ?>
            <div class="col-xs-12 col-sm-3 col-md-2 col-lg-2">
                <a class="item" href="<?=Url::toRoute(['catalog/subcat', 'slug' => $subcat->slug, 'cat' => $cat_slug, 'a' => $a]);?>">
                    <div class="item-img-wrapper">
                        <?=Html::img($subcat->thumb(null, 400), ['alt' => $subcat->title]);?>
                    </div>
                    <div class="item-title"><?=$subcat->title;?></div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>

app/views/catalog/datery-i-numeratory.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $subcats \yii\easyii\modules\catalog\api\CategoryObject[] */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\Html;
use yii\helpers\Url;
use yii\easyii\helpers\Image;

$this->title = Html::encode($cat->title);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    
    <div class="row auto-clear">
    <?php foreach($subcats as $subcat): ?>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-5ths">
            <a class="item" href="<?=Url::toRoute(['catalog/dn', 'slug' => $subcat->slug]);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($subcat->thumb(null, 350), ['alt' => $subcat->title]);?>
                </div>
                <div class="item-title"><?=$subcat->title;?></div>
            </a>
        </div>
    <?php endforeach; ?>
    <?php foreach($items as $item): ?>
        <?php
            if($item->slug === 'smennye-poduski'){
                $url_data = ['/smennye-poduski'];
            }
            else{
                $url_data = ['site/buy', 'id' => $item->id];
            }
        ?>
        
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-5ths">
            <a class="item" href="<?=Url::toRoute($url_data);?>">
                <div class="item-img-wrapper">
                    <?=Html::img(!empty($item->data->image) ?
                        Image::thumb('../uploads/' . $item->data->image, null, 350)
                            : $item->thumb(null, 350), ['alt' => $item->title]);?>
                </div>
                <div class="item-title"><?=$item->title;?></div>
            </a>
        </div>
    <?php endforeach; ?>
    </div>
</div>

app/views/catalog/dn.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $items \yii\easyii\modules\catalog\api\ItemObject[] */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\Html;
use yii\helpers\Url;

$this->title = Html::encode($cat->title);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row auto-clear">
        <?php foreach($items as $item): ?>
            <div class="сol-xs-12 col-sm-6">
                <a class="item" href="<?=Url::toRoute(['site/buy', 'id' => $item->id]);?>">
                    <div class="item-img-wrapper">
                        <?=Html::img($item->thumb(null, 350), ['alt' => $item->title]);?>
                    </div>
                </a>
            </div>
        <?php endforeach; ?>

        <?php $pagination = $cat->getPages(); ?>
        <?php if(!empty($pagination)): ?>
            <div class="clearfix margin-b-10"></div>
            <div class="col-xs-12 text-center">
                <?=$pagination;?>
            </div>
        <?php endif; ?>
    </div>
</div>

app/views/catalog/ekslibris.php
<?php
/* @var $item \yii\easyii\modules\catalog\api\ItemObject */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\ActiveForm;
use yii\widgets\MaskedInput;
use yii\bootstrap\Html;

$this->title = Html::encode($item->title);
$this->params['breadcrumbs'][] = ['label' => 'Образцы экслибрисов', 'url' => ['catalog/ekslibrisy']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row auto-clear">
        <div class="col-sm-6 col-sm-push-6">
            <?=Html::img($item->thumb(null, 300), ['class' => 'img-responsive center-block']);?>
        </div>
        <div class="col-sm-6 col-sm-pull-6">
            <?php $form = ActiveForm::begin();?>
            
            <?=$form->field($model, 'name')
                ->textInput(['placeholder' => $model->getAttributeLabel('name')])
                ->label(false);?>
            
            <?=$form->field($model, 'phone')
                ->textInput()
                ->label(false)
                ->widget(MaskedInput::className(), [
                    'mask' => '+7 (999) 999-99-99',
                    'options' => [
                        'placeholder' => $model->getAttributeLabel('phone'),
                        'class' => 'form-control',
                    ]
                ]);?>
            
            <?=$form->field($model, 'email')
                ->textInput(['placeholder' => $model->getAttributeLabel('email')])
                ->label(false);?>
            
            <?=$form->field($model, 'file')->fileInput();?>
            
            <?=$form->field($model, 'message')
                ->textarea(['placeholder' => $model->getAttributeLabel('message')])
                ->label(false);?>
            
            <div class="text-center">
                <?=Html::submitButton('Отправить', ['class' => 'btn btn-danger']);?>
            </div>
            
            <?php ActiveForm::end();?>
        </div>
    </div>
</div>

app/views/catalog/ekslibrisy.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $items \yii\easyii\modules\catalog\api\ItemObject[] */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\Html;
use yii\helpers\Url;

$this->title = Html::encode($cat->title);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row auto-clear">
        <?php foreach($items as $item): ?>
            <div class="col-xs-6 col-sm-4 col-md-5ths">
                <a class="item" href="<?=Url::toRoute(['catalog/ekslibris', 'slug' => $item->slug]);?>">
                    <div class="item-img-wrapper">
                        <?=Html::img($item->thumb(null, 350), ['alt' => $item->title]);?>
                    </div>
                    <div class="item-title"><?=$item->title;?></div>
                </a>
            </div>
        <?php endforeach; ?>

        <?php $pagination = $cat->getPages(); ?>
        <?php if(!empty($pagination)): ?>
            <div class="clearfix margin-b-10"></div>
            <div class="col-xs-12 text-center">
                <?=$pagination;?>
            </div>
        <?php endif; ?>
    </div>
</div>

app/views/catalog/index.php
<?php
/* @var $cats \yii\easyii\modules\catalog\api\CategoryObject[] */

$this->title = 'Каталог';
?>
<div class="container">
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row auto-clear">
        <?php foreach($cats as $cat): ?>
            <?=$this->render('//layouts/chunks/_cat', ['cat' => $cat]);?>
        <?php endforeach; ?>
    </div>
</div>

app/views/catalog/plombiry-i-plombiratory.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $items \yii\easyii\modules\catalog\api\ItemObject[] */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\Html;
use yii\helpers\Url;

$this->title = Html::encode($cat->title);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row auto-clear">
        <?php foreach($items as $item): ?>
            <div class="col-xs-6 col-sm-4 col-md-5ths col-lg-5ths">
                <a class="item" href="<?=Url::toRoute(['site/buy', 'id' => $item->id]);?>">
                    <div class="item-img-wrapper">
                        <?=Html::img($item->thumb(245, 245), ['alt' => $item->title]);?>
                    </div>
                    <div class="item-title">
                        <?=$item->title;?>
                        <?php if(!empty($item->data->priceinfo)):?>
                            <br>(<?=$item->data->priceinfo;?>)
                        <?php endif; ?>
                    </div>
                </a>
            </div>
        <?php endforeach; ?>

        <?php $pagination = $cat->getPages(); ?>
        <?php if(!empty($pagination)): ?>
            <div class="clearfix margin-b-10"></div>
            <div class="col-xs-12 text-center">
                <?=$pagination;?>
            </div>
        <?php endif; ?>
    </div>
</div>

app/views/catalog/stamps.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $stampy \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $by_scetch \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $faximile \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $ekslibrisy \yii\easyii\modules\catalog\api\CategoryObject */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\Html;
use yii\helpers\Url;

$this->title = Html::encode($cat->title);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row auto-clear">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
            <a class="item" href="<?=Url::toRoute(['catalog/cat', 'slug' => $by_scetch->slug]);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($by_scetch->thumb(null, 400), ['alt' => $by_scetch->title]);?>
                </div>
                <div class="item-title"><?=$by_scetch->title;?></div>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
            <a class="item" href="<?=Url::toRoute(['catalog/stampy']);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($stampy->thumb(null, 400), ['alt' => $stampy->title]);?>
                </div>
                <div class="item-title"><?=$stampy->title;?></div>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-2">
            <a class="item" href="<?=Url::toRoute(['catalog/cat', 'slug' => $faximile->slug]);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($faximile->thumb(null, 400), ['alt' => $faximile->title]);?>
                </div>
                <div class="item-title"><?=$faximile->title;?></div>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-2">
            <a class="item" href="<?=Url::toRoute(['catalog/ekslibrisy']);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($ekslibrisy->thumb(null, 400), ['alt' => $ekslibrisy->title]);?>
                </div>
                <div class="item-title"><?=$ekslibrisy->title;?></div>
            </a>
        </div>
    </div>
</div>

app/views/catalog/stampy-tools.php
<?php
/* @var $cat \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $items \yii\easyii\modules\catalog\api\ItemObject[] */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\Html;
use yii\helpers\Url;

$this->title = 'Образцы оснасток';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    
    <div class="row auto-clear">
        <?php foreach($items as $item): ?>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <a class="item" href="<?=Url::toRoute(['site/buy', 'id' => $item->id]);?>">
                    <div class="item-img-wrapper">
                        <?=Html::img($item->thumb(null, 350), ['alt' => $item->title]);?>
                    </div>
                    <div class="item-title"><?=$item->title;?></div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>


    <?php $pagination = $cat->getPages(); ?>
    <?php if(!empty($pagination)): ?>
        <div class="clearfix margin-b-10"></div>
        <div class="col-xs-12 text-center">
            <?=$pagination;?>
        </div>
    <?php endif; ?>
</div>

app/views/catalog/subcat.php
<?php
/* @var $subcat \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $items \yii\easyii\modules\catalog\api\ItemObject[] */

use yii\widgets\Breadcrumbs;
use app\helpers\CatalogHelper;
use yii\bootstrap\Html;

$this->title = Html::encode($subcat->title);
$parent = CatalogHelper::getParentCat($subcat);
$this->params['breadcrumbs'][] = ['label' => 'Варианты', 'url' => ['catalog/cat', 'slug' => $parent->slug]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center"><?=$this->title;?></h2>
    <div class="row auto-clear">
        <?php foreach($items as $item): ?>
            <div class="col-xs-6 col-sm-4 col-md-5ths">
                <?=$this->render('//layouts/chunks/_item',
                    ['item' => $item]);?>
            </div>
        <?php endforeach; ?>

        <?php $pagination = $subcat->getPages(); ?>
        <?php if(!empty($pagination)): ?>
            <div class="clearfix margin-b-10"></div>
            <div class="col-xs-12 text-center">
                <?=$pagination;?>
            </div>
        <?php endif; ?>
    </div>
</div>