app/controllers/CatalogController.php
<?php

namespace app\controllers;

use Yii;
use yii\easyii\modules\catalog\api\Catalog;
use yii\easyii\modules\catalog\models\Category;
use yii\easyii\modules\catalog\api\CategoryObject;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use app\helpers\CatalogHelper;


class CatalogController extends \yii\web\Controller
{
    public function actionIndex(){
        $cat_objects = Category::find()
            ->where(['id' => [1,2,3,4,5]])
            ->orderBy(['order_num' => SORT_ASC])
            ->all();
        $cats = ArrayHelper::map($cat_objects, 'id', function($cat){
            return new CategoryObject($cat);
        });
        
        
        return $this->render('index', [
            'cats' => $cats,
        ]);
    }
    
    
    public function actionCat($slug){
        $cat = Catalog::cat($slug);
        if(!$cat){
            throw new NotFoundHttpException('Категория не найдена.');
        }
        $child_cats = array_filter($cat->getChildren(), function($cat){
            return $cat->id != '26';
        });
        
        $items = null;
        if(!count($child_cats)){
            $items = $cat->getItems([
                'pagination' => ['defaultPageSize' => 16],
                'orderBy' => ['id' => SORT_ASC],
            ]);
        }
        
        $osnastki = null;
        if($slug == 'pecati'){
            $osnastki_objects = Category::find()
                ->where(['id' => [22,23,24,25]])
                ->orderBy(['order_num' => SORT_ASC])
                ->all();
            $osnastki = ArrayHelper::map($osnastki_objects, 'id', function($cat){
                $cat->parent = 3;
                return new CategoryObject($cat);
            });
        }
        
        // ВСЕ КАТЕГОРИИ (ДЛЯ МЕНЮ)
        $all_cats_objects = Category::find()
            ->where(['id' => [1,2,3,4,5]])
            ->select(['id', 'slug', 'title'])
            ->orderBy(['order_num' => SORT_ASC])
            ->all();
        $all_cats = ArrayHelper::map($all_cats_objects, 'id', function($cat){
            return new CategoryObject($cat);
        });
        
        $form_model = new \app\models\forms\CatalogForm();
        if(Yii::$app->request->isAjax){
            if($form_model->load(Yii::$app->request->post()) && $form_model->validate()){
                $form_model->save();
                return $this->asJson($form_model->toArray());
            }
        }
        
        return $this->render('cat', [
            'cat' => $cat,
            'child_cats' => $child_cats,
            'osnastki' => $osnastki,
            'all_cats' => $all_cats,
            'items' => $items,
            'form_model' => $form_model,
        ]);
    }
    
    
    
    
    public function actionSubcat($slug){
        $subcat = Catalog::cat($slug);
        $items = $subcat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        
        $form_model = new \app\models\forms\CatalogForm();
        if(Yii::$app->request->isAjax){
            if($form_model->load(Yii::$app->request->post()) && $form_model->validate()){
                $form_model->save();
                return $this->asJson($form_model->toArray());
            }
        }
        
        return $this->render('subcat', [
            'subcat' => $subcat,
            'items' => $items,
            'form_model' => $form_model,
        ]);
    }
    
    
    public function actionTools(){
        return $this->render('tools', [
            'tool_cats' => CatalogHelper::getToolCats(),
        ]);
    }
    
    public function actionToolsExamples($slug, $a = null){
        if(CatalogHelper::getToolCatConfig($slug, 'hidden') && $a !== null){
            CatalogHelper::buyHiddenItem($slug);
            if($a === 'buy'){
                $this->redirect(['/shopcart']);
            }
            else{
                $this->redirect(['/catalog/' . $a . '?a=buy']);
            }
        }
        $category = Catalog::cat($slug);
        return $this->render('tools-examples', [
            'category' => $category,
            'cat_config' => CatalogHelper::getToolCatConfig($slug),
        ]);
    }
    
    public function actionStamps(){
        return $this->render('stamps', [
            'cat' => Catalog::cat('stamps'),
            'by_scetch' => Catalog::cat('by-scetch'),
            'stampy' => Catalog::cat('stampy'),
            'faximile' => Catalog::cat('faximile'),
            'ekslibrisy' => Catalog::cat('ekslibrisy'),
        ]);
    }
    
    public function actionByScetch(){
        $path_info = explode('/', Yii::$app->request->getPathInfo());
        $slug = $path_info[count($path_info) - 1];
        $cat = Catalog::cat($slug);
        $model = new \app\models\ByScetchForm(['form_title' => $cat->title]);
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        return $this->render('by-scetch', [
            'cat' => $cat,
            'model' => $model,
        ]);
    }
    
    public function actionPlombiryIPlombiratory(){
        $cat = Catalog::cat('plombiry-i-plombiratory');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('plombiry-i-plombiratory', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionStampyTools(){
        $cat = Catalog::cat('stampy-tools');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('stampy-tools', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionEkslibrisy(){
        $cat = Catalog::cat('ekslibrisy');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 10],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('ekslibrisy', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionEkslibris($slug){
        $item = Catalog::get($slug);
        $model = new \app\models\EkslibrisForm([
            'form_title' => 'Экслибрис (' . $item->title . ')'
        ]);
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        return $this->render('ekslibris', [
            'item' => $item,
            'model' => $model,
        ]);
    }
    
    
    public function actionStampy(){
        $cat = Catalog::cat('stampy');
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 12],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('stampy', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    public function actionDateryINumeratory(){
        $categories = Category::find()->where(['in', 'slug', [
            'stampy-samonabornye',
            'pecati-samonabornye',
            'datery',
            'numeratory',
            'datery-so-svobodnym-polem',
            'avtomaticeskie-numeratory',
            'samonabornyj-dater',
            'smennye-poduski',
        ]])->orderBy(['id' => SORT_ASC])->all();
        $subcats = array_map(function($category){
            return new CategoryObject($category);
        }, $categories);
        $different = Catalog::cat('datery-different');
        return $this->render('datery-i-numeratory', [
            'cat' => Catalog::cat('datery-i-numeratory'),
            'items' => $different->getItems(['orderBy' => ['id' => SORT_ASC]]),
            'subcats' => $subcats,
        ]);
    }
    public function actionDn($slug){
        $cat = Catalog::cat($slug);
        $items = $cat->getItems([
            'pagination' => ['defaultPageSize' => 4],
            'orderBy' => ['id' => SORT_ASC],
        ]);
        return $this->render('dn', [
            'cat' => $cat,
            'items' => $items,
        ]);
    }
    
    public function actionSmennyePoduski(){
        $request = Yii::$app->request;
        if(!empty($request->post('form')) && !empty($request->post('id'))){
            return $this->redirect(['site/buy', 'id' => $request->post('id')]);
        }
        return $this->render('smennye-poduski', [
            'cat' => Catalog::cat('smennye-poduski'),
            'grm' => Catalog::cat('sp-grm'),
            'colop' => Catalog::cat('sp-colop'),
            'trodat' => Catalog::cat('sp-trodat'),
        ]);
    }
}

app/views/site/choose.php
<?php
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\widgets\MaskedInput;

$this->title = 'Заказ';
?>
<div class="container">
    <div class="row padding-t-30">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <?php $form = ActiveForm::begin([
                'action' => ['/call?r=1'],
                'id' => 'o-callback',
            ]);?>
            <div style="height:130px;">
                <h5 class="text-center">
                    Оставьте ваш номер телефона
                </h5>
                <p class="text-center">
                    и через 8 секунд наш менеджер позвонит
                    Вам и быстро оформит заказ!
                </p>
            </div>
            
            <?=$form->field($callback_model, 'phone', ['options' => ['class' => 'text-center']])
                ->textInput()
                ->widget(MaskedInput::className(),[
                    'mask' => '+7 (999) 999-99-99'
                ]);?>
            <div class="form-group text-center">
                <?=Html::submitButton('Перезвонить мне', ['class' => 'btn btn-info']);?>
            </div>
            
            <?php ActiveForm::end();?>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <?php $form = ActiveForm::begin([
                'id' => 'o-continue',
            ]);?>
            <div style="height:130px;">
                <h5 class="text-center">Оформить заказ онлайн</h5>
                <ul class="margin-b-20">
                    <li>Оплата по счету</li>
                    <li>Оплата карточкой на сайте</li>
                    <li>Оплата в офисе</li>
                </ul>
            </div>
            
            <?=$form->field($choose_model, 'phone', ['options' => ['class' => 'text-center']])
                ->textInput()
                ->widget(MaskedInput::className(),[
                    'mask' => '+7 (999) 999-99-99'
                ]);?>
            <?=Html::activeHiddenInput($choose_model, 'a');?>
            <div class="form-group text-center">
                <?=Html::submitButton('Продолжить<br>оформление заказа', ['class' => 'btn btn-info']);?>
            </div>
            
            <?php ActiveForm::end();?>
        </div>
    </div>
</div>

app/views/site/error.php
<?php
use yii\bootstrap\Html;
$this->title = 'Произошла ошибка';
?>
<div class="content-sm container">
    <div class="row">
        <div class="col-sm-4 margin-b-30">
            <h3><?=nl2br(Html::encode($message));?></h3>
        </div>
    </div>
</div>

app/views/site/index.php
<?php
/* @var $cats \yii\easyii\modules\catalog\api\CategoryObject[] */
/* @var $pechati \yii\easyii\modules\catalog\api\CategoryObject[] */
/* @var $tool_cats \yii\easyii\modules\catalog\api\CategoryObject[] */
/* @var $stampy \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $by_scetch \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $faximile \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $ekslibrisy \yii\easyii\modules\catalog\api\CategoryObject */
/* @var $uslugi \yii\easyii\modules\gallery\api\PhotoObject[] */
/* @var $partners \yii\easyii\modules\gallery\api\PhotoObject[] */
/* @var $callback_model \app\models\forms\CallbackForm */

$asset = \app\assets\AppAsset::register($this);
use yii\helpers\Url;
use yii\bootstrap\Html;
use yii\bootstrap\Modal;
use app\helpers\CatalogHelper;

?>
<?=$this->render('chunks/_offer', ['callback_model' => $callback_model]);?>


<div class="container container-first">
    <a class="anchor" id="catalog"></a>
    <h2 class="text-center">Каталог продукции</h2>
    <div class="row">
    <?php foreach($cats as $cat): ?>
        <div class="col-xs-12 col-sm-6 col-md-3">
            <a class="item" href="<?=Url::to(['/catalog/cat', 'slug' => $cat->slug]);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($cat->thumb(null, 400), ['alt' => $cat->title]);?>
                </div>
                <div class="item-title"><?=$cat->title;?></div>
            </a>
        </div>
    <?php endforeach; ?>
    </div>
</div>


<div class="container">
    <a class="anchor" id="prints"></a>
    <h2 class="text-center">Варианты печатей и штампов</h2>
    <div class="row auto-clear margin-b-20">
        <?php foreach($pechati as $pechat): ?>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
                <a class="item" href="<?=Url::toRoute(['catalog/subcat', 'cat' => $pechat->model->parent,  'slug' => $pechat->slug]);?>">
                    <div class="item-img-wrapper">
                        <?=Html::img($pechat->thumb(null, 400), ['alt' => $pechat->title]);?>
                    </div>
                    <div class="item-title"><?=$pechat->title;?></div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="row auto-clear">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
            <a class="item" href="<?=Url::toRoute(['catalog/cat', 'slug' => $by_scetch->slug]);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($by_scetch->thumb(null, 400), ['alt' => $by_scetch->title]);?>
                </div>
                <div class="item-title"><?=$by_scetch->title;?></div>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
            <a class="item" href="<?=Url::toRoute(['catalog/stampy']);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($stampy->thumb(null, 400), ['alt' => $stampy->title]);?>
                </div>
                <div class="item-title"><?=$stampy->title;?></div>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-2">
            <a class="item" href="<?=Url::toRoute(['catalog/cat', 'slug' => $faximile->slug]);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($faximile->thumb(null, 400), ['alt' => $faximile->title]);?>
                </div>
                <div class="item-title"><?=$faximile->title;?></div>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-2">
            <a class="item" href="<?=Url::toRoute(['catalog/ekslibrisy']);?>">
                <div class="item-img-wrapper">
                    <?=Html::img($ekslibrisy->thumb(null, 400), ['alt' => $ekslibrisy->title]);?>
                </div>
                <div class="item-title"><?=$ekslibrisy->title;?></div>
            </a>
        </div>
    </div>
    
</div>


<div class="container">
    <a class="anchor" id="equipment"></a>
    <h2 class="text-center">Варианты оснасток</h2>
    <div class="row">
        <?php $i = 0; ?>
        <?php foreach($tool_cats as $tool_cat): ?>
            <?php
                $variant = $i + 1;
                $a = Yii::$app->request->get('a');
            ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <a class="item" href="<?=Url::toRoute(['catalog/tools-examples', 'slug' => $tool_cat->slug, 'a' => 'pecati', 'b' => 'choose']);?>">
                    <div class="item-img-wrapper">
                        <?=Html::img($tool_cat->thumb(null, 400), ['alt' => $tool_cat->title]);?>
                    </div>
                    <div class="item-title"><?=$tool_cat->title;?></div>
                    <div class="item-flying-info">
                        <div class="item-flying-info-inner">
                            <span class="item-flying-info-bottom">
                                от <?=CatalogHelper::getMinPrice($tool_cat);?> руб.
                            </span>
                        </div>
                    </div>
                </a>
            </div>
            
            <?php $i++;?>
        <?php endforeach; ?>
    </div>
</div>

<div class="container text-center">
    <h2>
        О гарантии миллион оттисков или 10 лет
        <br class="hidden-xs">и почему это важно?
    </h2>
    <p style="font-size:19px;">
        Важно потому, что в результате длительного использования клише печати
        практически не подвергаются износу, потому что мы изготавливаем его
        из высококачественной резины производства США,
        специально предназначенной для такого большого количества оттисков.
    </p>
</div>


<a class="anchor" id="reviews"></a>
<div class="container">
    <h2 class="text-center">Отзывы наших клиентов</h2>
    <div class="swiper-container swiper" data-slides-per-view="4">
        <div class="swiper-wrapper">
            <?php foreach($comments as $comment): ?>
                <?=$this->render('//site/chunks/_carousel_comment', ['comment' => $comment]);?>
            <?php endforeach; ?>
        </div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</div>


<div class="container">
    <a class="anchor" id="partners"></a>
    <h2 class="text-center">Партнеры</h2>
    <div class="swiper-container" data-slides-per-view="4">
        <div class="swiper-wrapper">
            <?php foreach($partners as $partner): ?>
                <?=$this->render('//site/chunks/_gallery_partner', ['partner' => $partner]);?>
            <?php endforeach; ?>
        </div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</div>

<div class="container container-last">
    <a class="anchor" id="service"></a>
    <h2 class="text-center">Другие услуги</h2>
    <div class="swiper-container swiper-other-services" data-slides-per-view="3">
        <div class="swiper-wrapper">
            <?php foreach($uslugi as $slide): ?>
                <?=$this->render('//site/chunks/_service_slide', ['slide' => $slide]);?>
            <?php endforeach; ?>
        </div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</div>


<?php Modal::begin([
    'id' => 'reviews-image-modal',
    'header' => '<h4 class="margin-b-0 text-center" id="reviews-image-title"></h4>',
    'size' => Modal::SIZE_DEFAULT,
]);?>

<div class="row">
    <div class="col-xs-12">
        <img id="reviews-image" class="img-thumbnail center-block">
    </div>
</div>

<?php Modal::end();?>

<script>
    function reviewsImageModal(image_src, title){
        document.getElementById('reviews-image').src = image_src;
        document.getElementById('reviews-image-title').innerHTML = title;
    };
</script>
<?php
$this->registerJs(<<<JS
    jQuery('#pecati-phone, #pecati-i-stampy-phone, #metal-phone').inputmask('+7 (999) 999-99-99');
JS
);
?>

app/views/site/message.php
<?php
use yii\bootstrap\Html;
?>
<div class="container text-center">
    <a class="anchor" id="catalog"></a>
    <h2><?=$title;?></h2>
    <h3 class="margin-b-40"><?=$message;?></h3>
    <p><?=Html::a('Перейти на Главную', ['/'], ['class' => 'btn btn-info btn-lg']);?></p>
</div>

app/views/site/order-type.php
<?php
/** @var $category string */

/** @var $form_model \app\models\forms\CallbackForm */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Как вам удобнее сделать заказ?';
?>
<div class="bg-color-sky-dark-blue">
    <div class="content-sm container">
        <div class="row row-space-1">
            <div class="col-sm-4 sm-margin-b-2">
                <div class="pricing">
                    <div class="margin-b-30">
                        <i class="pricing-icon fa fa-phone" aria-hidden="true"></i>
                        <h2>По телефону</h2>
                    </div>
                    <ul class="list-unstyled pricing-list margin-b-50">
                        <li class="pricing-list-item"><b>Перезвоним Вам за 8 секунд</b></li>
                    </ul>
                    <?php $form = ActiveForm::begin([
                        'action' => ['/call'],
                        'fieldConfig' => [
                            'options' => ['class' => 'input-parent'],
                            'template' => '{input}{error}',
                            'inputOptions' => [
                                'class' => 'form-control content-input margin-b-20',
                            ]
                        ],
                    ]); ?>
                    <?= $form->field($form_model, 'phone')
                        ->widget(\yii\widgets\MaskedInput::className(), [
                            'mask' => '+7 (999) 999 99 99',
                            'options' => [
                                'autocomplete' => 'off',
                                'class' => 'form-control content-input margin-b-20',
                                'placeholder' => $form_model->getAttributeLabel('phone')
                            ],
                        ]); ?>

                    <?= Html::submitButton(
                        'Жду звонка',
                        [
                            'name' => 'OrderTypeForm[order_type]',
                            'value' => 'call',
                            'class' => 'btn-theme btn-theme-sm btn-base-bg text-uppercase',
                        ]
                    ); ?>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
            <div class="col-sm-4 sm-margin-b-2">
                <div class="pricing pricing-active">
                    <div class="margin-b-30">
                        <i class="pricing-icon fa fa-shopping-basket" aria-hidden="true"></i>
                        <h2>Онлайн заказ</h2>
                    </div>
                    <ul class="list-unstyled pricing-list margin-b-80">
                        <li class="pricing-list-item">Быстро</li>
                        <li class="pricing-list-item">Просто</li>
                        <li class="pricing-list-item">Удобно</li>
                        <li class="pricing-list-item"><b>Со скидкой 10%</b></li>
                    </ul>
                    <?= Html::a(
                        'Перейти к оформлению',
                        ['/catalog/cat', 'slug' => $category],
                        [
                            'class' => 'btn-theme btn-theme-sm btn-base-bg text-uppercase'
                        ]
                    ); ?>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="pricing">
                    <div class="margin-b-30">
                        <i class="pricing-icon icon-note"></i>
                        <h2>Другие способы</h2>
                    </div>
                    <ul class="list-unstyled pricing-list margin-b-50">
                        <li class="pricing-list-item">
                            <a href="mailto:site@fortex-rostov.ru">
                                <span><i class="mail fa fa-envelope-o" aria-hidden="true"></i></span>
                                Email:<br/>site@fortex-rostov.ru
                            </a>
                        </li>
                        <li class="pricing-list-item">
                            <a href="#">
                                <span><i class="whatsapp fa fa-whatsapp" aria-hidden="true"></i></span>
                                WhatsApp
                            </a>
                        </li>
                        <li class="pricing-list-item">
                            <a href="#">
                                <span><i class="viber icon-call-out"></i></span>
                                Viber
                            </a>
                        </li>
                        <li class="pricing-list-item">
                            <a href="#">
                                <span><i class="telegram fa fa-telegram" aria-hidden="true"></i></span>
                                Telegram
                            </a>
                        </li>
                    </ul>
                    <ul>
                </div>
            </div>
        </div>
    </div>
</div>

<?=$this->render('//layouts/chunks/_popular_slider');?>

app/views/site/partners.php
<?php
$this->title = 'Наши партнеры';
?>
<div class="container">
    <div class="row">
        <?php $index = 0; ?>
        <?php foreach($partners as $partner): ?>
            <?=$this->render('//site/chunks/_gallery_partner_full', [
                'partner' => $partner,
                'index' => $index,
            ]);?>
            <?php $index++; ?>
        <?php endforeach; ?>
    </div>
</div>

app/views/site/report.php
<table cellspacing="5">
    <?php foreach($form_info as $label => $value): ?>
        <tr>
            <td><b><?=$label;?>:</b></td>
            <td><?=$value;?></td>
        </tr>
    <?php endforeach; ?>
</table>

app/views/site/shopcart.php
<?php
use yii\widgets\Breadcrumbs;
use yii\bootstrap\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Оформление заказа';
$this->params['breadcrumbs'][] = $this->title;

if(isset($order_info->template)):

?>
<div class="container shopcart">
    <?=Breadcrumbs::widget([
        'homeLink' => ['label' => 'Фортекс', 'url' => '/'],
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
    ]);?>
    <h2 class="text-center" style="text-transform:none;"><?=$this->title;?></h2>
    
    <?php $form = ActiveForm::begin([
        'id' => 'shopcart-form'
    ]); ?>
    
    <?=$this->render('shopcart/' . $order_info->template, [
        'form' => $form,
        'shopcart_model' => $shopcart_model,
        'order_info' => $order_info,
        'urgency_info' => $urgency_info,
        'delivery_price' => $delivery_price,
        'min_price_free_delivery' => $min_price_free_delivery,
    ]);?>
    
    <?php ActiveForm::end(); ?>
</div>
<script>
    window.additional_price = function(){return 0;};
    window.additional_item_price = function(){return 0;};
    window.alternative_price = function(){return 0;};
</script>
<?php
$prefix = strtolower($shopcart_model->formName());
$prefix .= strlen($prefix) > 0 ? '-' : '';

$this->registerJs(<<<JS
    
    window.shopcartCost = function(){
        var alternative_price = window.alternative_price(),
            urgency_price = parseInt(jQuery('#{$prefix}urgency').find(':selected').data('urgency_price')),
            delivery_price = jQuery('#{$prefix}delivery').val() == '2' ? {$delivery_price} : 0,
            count_field = jQuery('#{$prefix}count'),
            cost = (alternative_price > 0) ? alternative_price : parseInt(count_field.data('cost')),
            count = parseInt(count_field.val()),
            total = (urgency_price + cost + window.additional_item_price()) * count;
        
        total += window.additional_price();
        total += (total < $min_price_free_delivery) ? delivery_price : 0;
        document.getElementById('shopcart-cost').innerHTML = total;
    };
    
    jQuery('#{$prefix}count').on('product-count.change', shopcartCost);
    
    jQuery('#{$prefix}delivery').on('change', function(){
        var da_field = document.getElementById('delivery_address');
        if(jQuery(this).val() == '2'){
            da_field.disabled = false;
        }
        else{
            da_field.disabled = true;
        }
        shopcartCost();
    }).trigger('change');
    
    jQuery('#{$prefix}urgency').on('change', shopcartCost);
    
    jQuery('#button-2').on('click', function(){
        var company_f = jQuery('#{$prefix}company'),
            form = $('#shopcart-form');
        if(company_f.length && !jQuery.trim(company_f.val()).length){
            form.yiiActiveForm('updateMessages', {
                'company': ['Заполните поле "Название организации"']
            }, true);
            jQuery('html, body').animate({
                scrollTop: jQuery('.has-error').first().offset().top - 100
            }, 300);
            return false;
        }
    });
    
JS
);
?>
<?php else: ?>

<div class="container text-center">
    <h2>На данный момент ваша корзина пуста</h2>
    <p>
        <?=Html::a('На главную', ['/'], ['class' => 'btn btn-info btn-lg']);?>
    </p>
</div>

<?php endif; ?>